name: 'GitIgnore Parser'
description: 'GitHub Action to parse a .gitignore file for information'
author: 'Derek Kershner'
inputs:
  path: 
    description: 'The location of the .gitignore file from the repo root, with no . and no need for the filename.'
    default: './'
    required: false
  includes_lines: 
    description: 'Comma-delimited string of what the gitignore must include'
    default: ''
    required: false
  fail_if_not_found: 
    description: 'true/false to indicate whether the workflow should fail if a string in includes_lines is not found'
    default: 'true'
    required: false
outputs:
  gitignored:
    description: 'A Comma-delimited string containing all lines in gitignore'
  all_lines_included:
    description: 'Returns a boolean representing whether all of the lines in includes_lines were indeed included'
  lines_not_included:
    description: 'A Comma-delimited string containing all of the lines from includes_lines that were not included'
  
runs:
  using: 'node12'
  main: 'dist/index.js'
