name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: 'gitignore-parser'
        with:
          ignored_includes: "node_modules,lib/**/*"
      # Will fail if it doesn't contain either, but outputs are also present
      - name: Print whether .gitignore contains above
        run: echo ${{ steps.gitignore-parser.outputs.all_included }}
  auto-approve-pr:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.event == 'pull_request' && github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'dkershner6'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
