# Only run when new semver tag is pushed
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

name: Move release tags

jobs:
  update-release-tags:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2
        # Get complete history
        with:
          fetch-depth: 0

      - name: Update release tags for latest major and minor releases
        uses: bewuethr/release-tracker-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}